import { useCallback, useEffect, useState } from 'react';
import { ConfirmSwitch } from '../components/ConfirmSwitch';
import { SectorQueue } from '../components/SectorQueue';
import { activateOrder, finishOrder, getSectorOrders, switchOrder, TOTAL_SECTORS, type Order } from '../services/ordersService';

export function SectorDashboard({ sectorId }: { sectorId: number }) {
  const [orders, setOrders] = useState<Order[]>([]); const [pendingOrderId, setPendingOrderId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setOrders(await getSectorOrders(sectorId)); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo cargar el sector.'); } finally { setLoading(false); } }, [sectorId]);
  useEffect(() => { void load(); }, [load]);
  const activeOrder = orders.find((order) => order.status === 'active'); const pendingOrders = orders.filter((order) => order.status === 'pending');
  async function run(action: () => Promise<void>, successMessage = '') { setBusy(true); setError(''); setMessage(''); try { await action(); await load(); setMessage(successMessage); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo completar la operación.'); } finally { setBusy(false); } }
  function selectOrder(orderId: string) { if (activeOrder) setPendingOrderId(orderId); else void run(() => activateOrder(orderId, sectorId)); }
  function confirmSwitch() { if (!activeOrder || !pendingOrderId) return; void run(async () => { await switchOrder(activeOrder.id, pendingOrderId, sectorId); setPendingOrderId(null); }); }
  const isFinalSector = sectorId === TOTAL_SECTORS;
  return <section className="dashboard-card"><div className="dashboard-heading"><div><p className="eyebrow">CENTRO DE OPERACIONES</p><h2>Sector {sectorId}</h2><p className="muted">Gestiona la cola de pedidos de tu estación.</p></div><div className="sector-badge">S{String(sectorId).padStart(2, '0')}</div></div><div className="sector-flow" aria-label="Flujo de sectores">{Array.from({ length: TOTAL_SECTORS }, (_, index) => { const currentSector = index + 1; return <span key={currentSector} className={currentSector === sectorId ? 'flow-step current' : currentSector < sectorId ? 'flow-step complete' : 'flow-step'}>{currentSector}</span>; })}</div>{error && <p role="alert" className="error">{error}</p>}{message && <p role="status" className="status-message">{message}</p>}{loading ? <p>Cargando pedidos...</p> : <><div className="dashboard-stats"><div><span>Pedidos en cola</span><strong>{pendingOrders.length}</strong></div><div><span>Pedido activo</span><strong>{activeOrder ? '1' : '0'}</strong></div><div><span>Estación</span><strong>{sectorId}/{TOTAL_SECTORS}</strong></div></div><section className="active-order"><div className="section-heading"><div><p className="eyebrow">EN PROCESO</p><h3>Pedido activo</h3></div>{activeOrder && <span className="status-pill">Activo</span>}</div>{activeOrder ? <div className="active-order-content"><div><p className="order-code">{activeOrder.code}</p><p className="order-client">{activeOrder.client}</p><p className="order-product">{activeOrder.product} · {activeOrder.quantity} unidades</p></div><button disabled={busy} onClick={() => void run(() => finishOrder(activeOrder.id, sectorId), isFinalSector ? 'Pedido terminado correctamente.' : `Pedido enviado al sector ${sectorId + 1}.`)}>{isFinalSector ? 'Terminar pedido' : 'Enviar al sector ' + (sectorId + 1)}</button></div> : <p className="muted">No hay un pedido activo. Selecciona uno de la cola para comenzar.</p>}</section><section className="queue-section"><div className="section-heading"><div><p className="eyebrow">SIGUIENTES</p><h3>Cola de pedidos</h3></div><span className="queue-count">{pendingOrders.length} pendientes</span></div><SectorQueue orders={pendingOrders} hasActiveOrder={Boolean(activeOrder)} onActivate={selectOrder} busy={busy} /></section></>}{pendingOrderId && <ConfirmSwitch busy={busy} onConfirm={confirmSwitch} onCancel={() => setPendingOrderId(null)} />}</section>;
}
